Support newer esqueleto versions
This fixes the following compilation error:

    src/GTFS/Database.hs:76:1: error:
        Generating Persistent entities now requires the following language extensions:
    DerivingStrategies
    StandaloneDeriving
    UndecidableInstances
    Please enable the extensions by copy/pasting these lines into the top of your file:
    {-# LANGUAGE DerivingStrategies #-}
    {-# LANGUAGE StandaloneDeriving #-}
    {-# LANGUAGE UndecidableInstances #-}
    |
    76 | share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
    error: Bad exit status from /var/tmp/rpm-tmp.pHECku (%build)
        Bad exit status from /var/tmp/rpm-tmp.pHECku (%build)