Fix storing of time values
These times were formerly represented as text. I suppose it only
"worked" because SQLite or the Haskell wrapper was more forgiving that
it should have been. Anyway to avoid a broken test like:

   Exception: PersistMarshalError "Couldn't parse field `arrivalTime` from table `stop_time`. Failed to parse Haskell type `TimeOfDay`, but received PersistText \"32:00:00\""