Fixes out of date generated code from proto file
The builds were failing with:

    src/GTFS/Realtime/Internal/Com/Google/Transit/Realtime/VehiclePosition/OccupancyStatus.hs:89:6: error:
    • Couldn't match expected type ‘P'.EnumInfo’
                  with actual type ‘P'.Bool -> P'.EnumInfo’
    • Probable cause: ‘P'.EnumInfo’ is applied to too few arguments
      In the expression:
        P'.EnumInfo
          (P'.makePNF
             (P'.pack ".transit_realtime.VehiclePosition.OccupancyStatus")
             ["GTFS", "Realtime", "Internal"]
             ["Com", "Google", "Transit", "Realtime", ....]
             "OccupancyStatus")
          ["GTFS", "Realtime", "Internal", "Com", ....]
          [(0, "EMPTY"), (1, "MANY_SEATS_AVAILABLE"),
           (2, "FEW_SEATS_AVAILABLE"), (3, "STANDING_ROOM_ONLY"), ....]
      In an equation for ‘P'.reflectEnumInfo’:
          P'.reflectEnumInfo _
            = P'.EnumInfo
                (P'.makePNF
                   (P'.pack ".transit_realtime.VehiclePosition.OccupancyStatus")
                   ["GTFS", "Realtime", "Internal"]
                   ["Com", "Google", "Transit", ....]
                   "OccupancyStatus")
                ["GTFS", "Realtime", "Internal", ....]
                [(0, "EMPTY"), (1, "MANY_SEATS_AVAILABLE"),
                 (2, "FEW_SEATS_AVAILABLE"), ....]
      In the instance declaration for ‘P'.ReflectEnum OccupancyStatus’
   |
89 |    = P'.EnumInfo
   |      ^^^^^^^^^^^...

This updates the generated code from the proto file after running
a recent version of hprotoc over it.